<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\Homestead.Core\Homestead.Core.csproj" />
    <ProjectReference Include="..\Homstead.App\Homstead.App.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Config\" />
  </ItemGroup>

</Project>
